-- drop existing tables
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE TRADERS CASCADE CONSTRAINTS;
DROP TABLE ADMINS CASCADE CONSTRAINTS;
DROP TABLE ACCESS_DETAILS CASCADE CONSTRAINTS;
DROP TABLE COLLECTION_SLOTS CASCADE CONSTRAINTS;
DROP TABLE TRADER_TYPES CASCADE CONSTRAINTS;
DROP TABLE SHOPS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE OFFERS CASCADE CONSTRAINTS;
DROP TABLE BASKETS CASCADE CONSTRAINTS;
DROP TABLE BASKET_PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE INVOICES CASCADE CONSTRAINTS;
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;

-- drop existing sequence
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE CUSTOMERS_SEQ;
DROP SEQUENCE TRADERS_SEQ;
DROP SEQUENCE ADMINS_SEQ;
DROP SEQUENCE ACCESS_DETAILS_SEQ;
DROP SEQUENCE COLLECTION_SLOTS_SEQ;
DROP SEQUENCE TRADER_TYPES_SEQ;
DROP SEQUENCE SHOPS_SEQ;
DROP SEQUENCE PRODUCT_CATEGORIES_SEQ;
DROP SEQUENCE PRODUCTS_SEQ;
DROP SEQUENCE PRODUCT_REVIEWS_SEQ;
DROP SEQUENCE OFFERS_SEQ;
DROP SEQUENCE BASKETS_SEQ;
DROP SEQUENCE BASKET_PRODUCTS_SEQ;
DROP SEQUENCE INVOICES_SEQ;
DROP SEQUENCE PAYMENTS_SEQ;

-- drop existing triggers
DROP TRIGGER INSERT_USERS_ID;
DROP TRIGGER INSERT_CUSTOMERS_ID;
DROP TRIGGER INSERT_TRADERS_ID;
DROP TRIGGER INSERT_ADMINS_ID;
--DROP TRIGGER INSERT_ACCESS_DETAILS_ID;
DROP TRIGGER INSERT_COLLECTION_SLOTS_ID;
DROP TRIGGER INSERT_TRADER_TYPES_ID;
DROP TRIGGER INSERT_SHOPS_ID;
DROP TRIGGER INSERT_PRODUCT_CATEGORIES_ID;
DROP TRIGGER INSERT_PRODUCTS_ID;
DROP TRIGGER INSERT_PRODUCT_REVIEWS_ID;
DROP TRIGGER INSERT_OFFERS_ID;
DROP TRIGGER INSERT_BASKETS_ID;
--DROP TRIGGER INSERT_BASKET_PRODUCTS_ID;
DROP TRIGGER INSERT_INVOICES_ID;
DROP TRIGGER INSERT_PAYMENTS_ID;